name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    env:
        CI: true

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Cordova
      run: |
        npm install -g cordova
        npm install -g ionic
    
    - name: Install dependencies
      run: npm install
      
    - name: Run lint
      run: npm run lint
      
    # - name: Run Test
    #   run: npm run test

    - name: Build iOS
      run: |
        ionic cordova platform add ios
        ionic cordova prepare ios --prod
